#!/usr/bin/env bash

function usage () {
  echo
  echo "Usage"
  echo "  $0"
  echo
}

function message() {
    # $1 = type , $2 = message
    # Message types
    # 0 - info
    # 1 - warning
    # 2 - error
    if [ -z "${1}" ] || [ -z "${2}" ]; then
      return
    fi

    local RED="\e[31m"
    local GREEN="\e[32m"
    local YELLOW="\e[33m"
    local RESET="\e[0m"
    local MESSAGE_TYPE=""
    local MESSAGE=""
    MESSAGE_TYPE="${1}"
    MESSAGE="${2}"
    
    case ${MESSAGE_TYPE} in
      0) echo -e "  [${GREEN}+${RESET}] INFO: ${MESSAGE}";;
      1) echo -e "  [${YELLOW}*${RESET}] WARNING: ${MESSAGE}";;
      2) echo -e "  [${RED}!${RESET}] ERROR: ${MESSAGE}";;
      *) echo -e "  [?] UNKNOWN: ${MESSAGE}";;
    esac
}

echo "Rolling Rhino 🦏"

# Check if the user running the script is root
if [ "$(id -u)" -ne 0 ]; then
  message 2 "You need to be root."
  exit 1
fi

# Take command line arguments
while [ $# -gt 0 ]; do
  case "${1}" in
    -h|--h|-help|--help)
      usage
      exit 0;;
    *)
      message 2 "\"${1}\" is not a supported parameter."
      usage
      exit 1;;
  esac
done

if which lsb_release 1>/dev/null; then
  message 0 "lsb_release detected."
else
  message 2 "lsb_release not detected. Quitting."
  exit 1
fi

if grep -q devel /etc/apt/sources.list; then
  message 2 "Already tracking the devel series. Nothing to do."
  exit 1
fi

OS_ID=$(lsb_release --id --short)
if [ "${OS_ID}" == "Ubuntu" ]; then
  message 0 "Ubuntu detected."
else
  message 2 "${OS_ID} detected, which is not supported."
  exit 1
fi

OS_DESCRIPTION=$(lsb_release --description --short)
if [[ "${OS_DESCRIPTION}" == *"development branch"* ]]; then
  message 0 "${OS_DESCRIPTION} detected."
elif  [[ "${OS_DESCRIPTION}" == *"LTS"* ]]; then
  message 2 "${OS_DESCRIPTION} detected, which is not supported."
  exit 1
else
  message 2 "${OS_DESCRIPTION} detected, which is not supported."
  exit 1
fi

DESKTOP_FOUND=0
for META in kubuntu-desktop lubuntu-desktop ubuntu-desktop ubuntu-budgie-desktop ubuntukylin-desktop ubuntu-mate-desktop ubuntustudio-desktop xubuntu-desktop; do
  INSTALLED=$(apt list --installed "${META}" 2>/dev/null | grep installed)
  if [ -n "${INSTALLED}" ]; then
    message 0 "Detected ${META}"
    DESKTOP_FOUND=1
    break
  fi
done

if [ ${DESKTOP_FOUND} -eq 0 ]; then
  message 2 "Not desktop installed detected. Quitting."
  exit 1
fi